### PR TITLE
Add model relative path to CLI commands logs

### PR DESCRIPTION
**Pull request by lucasdutraf**
**Proposed changes**:
- Add model relative path to CLI commands logs
Resolving issue #6571

**Status (please check what you already did)**:
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Comment by Henrike100** [comment]
I think it would be good to write the changelog.

**Comment by Henrike100** [comment]
Also, change this:

`logger.info("Loading model {}...".format(model_relative_path))`

to this:

`logger.info(f"Loading model {model_relative_path}...")`

**Comment by lucasdutraf** [comment]
> Also, change this:
> 
> `logger.info("Loading model {}...".format(model_relative_path))`
> 
> to this:
> 
> `logger.info(f"Loading model {model_relative_path}...")`

Done @Henrike100 ! Thanks for your help! :smile:

**Review by arthurTemporim — APPROVED** [review]
Appears good to me :D

**Pull request merged**
